# Since DarkySky does not have icons available online to be used, the 'icon' value returned by the DarkSky API is mapped
# to a similar open weather icon. Open weather icons are available online and can be used in html with the following:
# <img src="http://openweathermap.org/img/w/[ICON_VALUE].png" alt="Image">
DARKSKY_TO_OPEN_WEATHER_ICON = {
        "clear-day": "01d",
        "clear-night": "01n",
        "rain": "09d",
        "snow": "13d",
        "sleet": "09d",
        "wind": "50d",
        "fog": "04d",
        "cloudy": "03d",
        "partly-cloudy-day": "02d",
        "partly-cloudy-night": "02n",
        "hail": "11d",
        "thunderstorm": "11d",
        "tornado": "11d"
}

# Gives current weather forecast -- basic data
def get_current_weather_basic(darkskyjson, city):
    current_weather = {
        "city": city,
        "icon": DARKSKY_TO_OPEN_WEATHER_ICON[darkskyjson["currently"]["icon"]],
        "time": darkskyjson["currently"]["time"],
        "summary": darkskyjson["currently"]["summary"],
        "precipProbability": darkskyjson["currently"]["precipProbability"],
        "temperature": darkskyjson["currently"]["temperature"],
        "humidity": darkskyjson["currently"]["humidity"],
        "windSpeed": darkskyjson["currently"]["windSpeed"],
        "windGust": darkskyjson["currently"]["windGust"],
        "visibility": darkskyjson["currently"]["visibility"],
    }
    return current_weather

# Gives current weather forecast -- all data
# See DarkSky documentation for json format: https://darksky.net/dev/docs
def get_current_weather_all(darkskyjson):
    return darkskyjson["currently"]

# Gives summary of weather for the day in hourly weather forecast. The hourly_weather object here will contain
# 7 different forecasts, with weather data from the present hour then every 3 hours.
def get_day_weather_basic(darkskyjson, city):
    hourly_weather = {
        "city": city,
        "daySummary": darkskyjson["hourly"]["summary"],
        "icon": DARKSKY_TO_OPEN_WEATHER_ICON[darkskyjson["hourly"]["icon"]],
        "0hrFromNow": {
            "summary": darkskyjson["hourly"]["data"][0]["summary"],
            "temperature": darkskyjson["hourly"]["data"][0]["temperature"],
            "humidity": darkskyjson["hourly"]["data"][0]["humidity"],
            "precipProbability": darkskyjson["hourly"]["data"][0]["precipProbability"],
            "windSpeed": darkskyjson["hourly"]["data"][0]["windSpeed"],
        },
        "3hrFromNow": {
            "summary": darkskyjson["hourly"]["data"][3]["summary"],
            "temperature": darkskyjson["hourly"]["data"][3]["temperature"],
            "humidity": darkskyjson["hourly"]["data"][3]["humidity"],
            "precipProbability": darkskyjson["hourly"]["data"][3]["precipProbability"],
            "windSpeed": darkskyjson["hourly"]["data"][3]["windSpeed"],
        },
        "6hrFromNow": {
            "summary": darkskyjson["hourly"]["data"][6]["summary"],
            "temperature": darkskyjson["hourly"]["data"][6]["temperature"],
            "humidity": darkskyjson["hourly"]["data"][6]["humidity"],
            "precipProbability": darkskyjson["hourly"]["data"][6]["precipProbability"],
            "windSpeed": darkskyjson["hourly"]["data"][6]["windSpeed"],
        },
        "9hrFromNow": {
            "summary": darkskyjson["hourly"]["data"][9]["summary"],
            "temperature": darkskyjson["hourly"]["data"][9]["temperature"],
            "humidity": darkskyjson["hourly"]["data"][9]["humidity"],
            "precipProbability": darkskyjson["hourly"]["data"][9]["precipProbability"],
            "windSpeed": darkskyjson["hourly"]["data"][9]["windSpeed"],
        },
        "12hrFromNow": {
            "summary": darkskyjson["hourly"]["data"][12]["summary"],
            "temperature": darkskyjson["hourly"]["data"][12]["temperature"],
            "humidity": darkskyjson["hourly"]["data"][12]["humidity"],
            "precipProbability": darkskyjson["hourly"]["data"][12]["precipProbability"],
            "windSpeed": darkskyjson["hourly"]["data"][12]["windSpeed"],
        },
        "15hrFromNow": {
            "summary": darkskyjson["hourly"]["data"][15]["summary"],
            "temperature": darkskyjson["hourly"]["data"][15]["temperature"],
            "humidity": darkskyjson["hourly"]["data"][15]["humidity"],
            "precipProbability": darkskyjson["hourly"]["data"][15]["precipProbability"],
            "windSpeed": darkskyjson["hourly"]["data"][15]["windSpeed"],
        },
        "18hrFromNow": {
            "summary": darkskyjson["hourly"]["data"][18]["summary"],
            "temperature": darkskyjson["hourly"]["data"][18]["temperature"],
            "humidity": darkskyjson["hourly"]["data"][18]["humidity"],
            "precipProbability": darkskyjson["hourly"]["data"][18]["precipProbability"],
            "windSpeed": darkskyjson["hourly"]["data"][18]["windSpeed"],
        },
    }
    return hourly_weather

# Gives weather data for day in hourly weather forecasts (over 40)
# See DarkSky documentation for json format: https://darksky.net/dev/docs
def get_day_weather_all(darkskyjson):
    return darkskyjson["hourly"]

# Gives summary of weather for the week by daily forecasts -- basic data
def get_week_weather_basic(darkskyjson, city):
    weekly_weather = {
        "city": city,
        "weekSummary": darkskyjson["daily"]["summary"],
        "icon": DARKSKY_TO_OPEN_WEATHER_ICON[darkskyjson["daily"]["icon"]],
        "day1": {
            "summary": darkskyjson["daily"]["data"][0]["summary"],
            "precipProbability": darkskyjson["daily"]["data"][0]["precipProbability"],
            "precipType" : darkskyjson["daily"]["data"][0]["precipType"],
            "temperatureHigh": darkskyjson["daily"]["data"][0]["temperatureHigh"],
            "temperatureLow": darkskyjson["daily"]["data"][0]["temperatureLow"],
            "humidity": darkskyjson["daily"]["data"][0]["humidity"],
            "windSpeed": darkskyjson["daily"]["data"][0]["windSpeed"],
            "windGust": darkskyjson["daily"]["data"][0]["windGust"],
            "visibility": darkskyjson["daily"]["data"][0]["visibility"]
        },
        "day2": {
            "summary": darkskyjson["daily"]["data"][1]["summary"],
            "precipProbability": darkskyjson["daily"]["data"][1]["precipProbability"],
            "precipType": darkskyjson["daily"]["data"][1]["precipType"],
            "temperatureHigh": darkskyjson["daily"]["data"][1]["temperatureHigh"],
            "temperatureLow": darkskyjson["daily"]["data"][1]["temperatureLow"],
            "humidity": darkskyjson["daily"]["data"][1]["humidity"],
            "windSpeed": darkskyjson["daily"]["data"][1]["windSpeed"],
            "windGust": darkskyjson["daily"]["data"][1]["windGust"],
            "visibility": darkskyjson["daily"]["data"][1]["visibility"]
        },
        "day3": {
            "summary": darkskyjson["daily"]["data"][2]["summary"],
            "precipProbability": darkskyjson["daily"]["data"][2]["precipProbability"],
            "precipType": darkskyjson["daily"]["data"][2]["precipType"],
            "temperatureHigh": darkskyjson["daily"]["data"][2]["temperatureHigh"],
            "temperatureLow": darkskyjson["daily"]["data"][2]["temperatureLow"],
            "humidity": darkskyjson["daily"]["data"][2]["humidity"],
            "windSpeed": darkskyjson["daily"]["data"][2]["windSpeed"],
            "windGust": darkskyjson["daily"]["data"][2]["windGust"],
            "visibility": darkskyjson["daily"]["data"][2]["visibility"]
        },
        "day4": {
            "summary": darkskyjson["daily"]["data"][3]["summary"],
            "precipProbability": darkskyjson["daily"]["data"][3]["precipProbability"],
            "precipType": darkskyjson["daily"]["data"][3]["precipType"],
            "temperatureHigh": darkskyjson["daily"]["data"][3]["temperatureHigh"],
            "temperatureLow": darkskyjson["daily"]["data"][3]["temperatureLow"],
            "humidity": darkskyjson["daily"]["data"][3]["humidity"],
            "windSpeed": darkskyjson["daily"]["data"][3]["windSpeed"],
            "windGust": darkskyjson["daily"]["data"][3]["windGust"],
            "visibility": darkskyjson["daily"]["data"][3]["visibility"]
        },
        "day5": {
            "summary": darkskyjson["daily"]["data"][4]["summary"],
            "precipProbability": darkskyjson["daily"]["data"][4]["precipProbability"],
            "precipType": darkskyjson["daily"]["data"][4]["precipType"],
            "temperatureHigh": darkskyjson["daily"]["data"][4]["temperatureHigh"],
            "temperatureLow": darkskyjson["daily"]["data"][4]["temperatureLow"],
            "humidity": darkskyjson["daily"]["data"][4]["humidity"],
            "windSpeed": darkskyjson["daily"]["data"][4]["windSpeed"],
            "windGust": darkskyjson["daily"]["data"][4]["windGust"],
            "visibility": darkskyjson["daily"]["data"][4]["visibility"]
        },
        "day6": {
            "summary": darkskyjson["daily"]["data"][5]["summary"],
            "precipProbability": darkskyjson["daily"]["data"][5]["precipProbability"],
            "precipType": darkskyjson["daily"]["data"][5]["precipType"],
            "temperatureHigh": darkskyjson["daily"]["data"][5]["temperatureHigh"],
            "temperatureLow": darkskyjson["daily"]["data"][5]["temperatureLow"],
            "humidity": darkskyjson["daily"]["data"][5]["humidity"],
            "windSpeed": darkskyjson["daily"]["data"][5]["windSpeed"],
            "windGust": darkskyjson["daily"]["data"][5]["windGust"],
            "visibility": darkskyjson["daily"]["data"][5]["visibility"]
        },
        "day7": {
            "summary": darkskyjson["daily"]["data"][6]["summary"],
            "precipProbability": darkskyjson["daily"]["data"][6]["precipProbability"],
            "precipType": darkskyjson["daily"]["data"][6]["precipType"],
            "temperatureHigh": darkskyjson["daily"]["data"][6]["temperatureHigh"],
            "temperatureLow": darkskyjson["daily"]["data"][6]["temperatureLow"],
            "humidity": darkskyjson["daily"]["data"][6]["humidity"],
            "windSpeed": darkskyjson["daily"]["data"][6]["windSpeed"],
            "windGust": darkskyjson["daily"]["data"][6]["windGust"],
            "visibility": darkskyjson["daily"]["data"][6]["visibility"]
        }
    }
    return weekly_weather

# Gives summary of weather for the week, and daily forecasts for the week -- all data
# See end of file for all data json structure -- DarkSky documentation for json format https://darksky.net/dev/docs
# appears to be outdated and slightly off.
def get_week_weather_all(darkskyjson):
    return darkskyjson["daily"]

# Example structure returned from get_day_weather_all:
#     'hourly': {   'data': [   {   'apparentTemperature': 86.88,
#                                   'cloudCover': 0.56,
#                                   'dewPoint': 68.41,
#                                   'humidity': 0.61,
#                                   'icon': 'partly-cloudy-day',
#                                   'ozone': 253.5,
#                                   'precipIntensity': 0,
#                                   'precipProbability': 0,
#                                   'pressure': 1017.52,
#                                   'summary': 'Partly Cloudy',
#                                   'temperature': 83.52,
#                                   'time': 1541440800, 1PM
#                                   'uvIndex': 5,
#                                   'visibility': 10,
#                                   'windBearing': 168,
#                                   'windGust': 5.13,
#                                   'windSpeed': 3.57
#                               },
#                                   ...
#                                   The structure containing all data includes over 40 entries for hourly weather data
#                                   Only the first and last are shown in this example to reduce size.
#                                   ...
#                               {
#                                 'apparentTemperature': 87.09,
#                                 'cloudCover': 0.34,
#                                'dewPoint': 66.67,
#                                'humidity': 0.55,
#                                'icon': 'partly-cloudy-day',
#                                'ozone': 264.47,
#                                'precipIntensity': 0,
#                                'precipProbability': 0,
#                                'pressure': 1015.92,
#                                'summary': 'Partly Cloudy',
#                                'temperature': 84.51,
#                                'time': 1541613600,
#                                'uvIndex': 5,
#                                'visibility': 10,
#                                'windBearing': 158,
#                                'windGust': 6.37,
#                                'windSpeed': 4.43
#                           }
#                    ],
#                   'icon': 'partly-cloudy-night',
#                   'summary': 'Mostly cloudy throughout the day.'
#     }

# Example structure returned from get_week_weather_all:
# 'daily': {
#
# 	'data': [
# {   'apparentTemperatureHigh': 87.79,
#                                  'apparentTemperatureHighTime': 1541448000,
#                                  'apparentTemperatureLow': 71.54,
#                                  'apparentTemperatureLowTime': 1541502000,
#                                  'apparentTemperatureMax': 87.79,
#                                  'apparentTemperatureMaxTime': 1541448000,
#                                  'apparentTemperatureMin': 73.56,
#                                  'apparentTemperatureMinTime': 1541397600,
#                                  'cloudCover': 0.53,
#                                  'dewPoint': 69.62,
#                                  'humidity': 0.79,
#                                  'icon': 'partly-cloudy-night',
#                                  'moonPhase': 0.93,
#                                  'ozone': 251.88,
#                                  'precipIntensity': 0.0007,
#                                  'precipIntensityMax': 0.0025,
#                                  'precipIntensityMaxTime': 1541462400,
#                                  'precipProbability': 0.19,
#                                  'precipType': 'rain',
#                                  'pressure': 1017.48,
#                                  'summary': 'Mostly cloudy throughout the day.',
#                                  'sunriseTime': 1541418318,
#                                  'sunsetTime': 1541457847,
#                                  'temperatureHigh': 84.84,
#                                  'temperatureHighTime': 1541448000,
#                                  'temperatureLow': 70.26,
#                                  'temperatureLowTime': 1541502000,
#                                  'temperatureMax': 84.84,
#                                  'temperatureMaxTime': 1541448000,
#                                  'temperatureMin': 72.24,
#                                  'temperatureMinTime': 1541397600,
#                                  'time': 1541394000,
#                                  'uvIndex': 5,
#                                  'uvIndexTime': 1541433600,
#                                  'visibility': 10,
#                                  'windBearing': 152,
#                                  'windGust': 7.79,
#                                  'windGustTime': 1541458800,
#                                  'windSpeed': 3.77},
# {   'apparentTemperatureHigh': 87.37,
#                                  'apparentTemperatureHighTime': 1541534400,
#                                  'apparentTemperatureLow': 68.53,
#                                  'apparentTemperatureLowTime': 1541588400,
#                                  'apparentTemperatureMax': 87.37,
#                                  'apparentTemperatureMaxTime': 1541534400,
#                                  'apparentTemperatureMin': 71.54,
#                                  'apparentTemperatureMinTime': 1541502000,
#                                  'cloudCover': 0.71,
#                                  'dewPoint': 68.59,
#                                  'humidity': 0.78,
#                                  'icon': 'partly-cloudy-day',
#                                  'moonPhase': 0.97,
#                                  'ozone': 257.27,
#                                  'precipIntensity': 0.0007,
#                                  'precipIntensityMax': 0.0042,
#                                  'precipIntensityMaxTime': 1541494800,
#                                  'precipProbability': 0.16,
#                                  'precipType': 'rain',
#                                  'pressure': 1016.57,
#                                  'summary': 'Mostly cloudy throughout the day.',
#                                  'sunriseTime': 1541504763,
#                                  'sunsetTime': 1541544209,
#                                  'temperatureHigh': 85,
#                                  'temperatureHighTime': 1541534400,
#                                  'temperatureLow': 67.39,
#                                  'temperatureLowTime': 1541588400,
#                                  'temperatureMax': 85,
#                                  'temperatureMaxTime': 1541534400,
#                                  'temperatureMin': 70.26,
#                                  'temperatureMinTime': 1541502000,
#                                  'time': 1541480400,
#                                  'uvIndex': 5,
#                                  'uvIndexTime': 1541523600,
#                                  'visibility': 10,
#                                  'windBearing': 162,
#                                  'windGust': 10.64,
#                                  'windGustTime': 1541512800,
#                                  'windSpeed': 2.99},
# {   'apparentTemperatureHigh': 87.69,
#                                  'apparentTemperatureHighTime': 1541620800,
#                                  'apparentTemperatureLow': 70.2,
#                                  'apparentTemperatureLowTime': 1541674800,
#                                  'apparentTemperatureMax': 87.69,
#                                  'apparentTemperatureMaxTime': 1541620800,
#                                  'apparentTemperatureMin': 68.53,
#                                  'apparentTemperatureMinTime': 1541588400,
#                                  'cloudCover': 0.25,
#                                  'dewPoint': 68.08,
#                                  'humidity': 0.79,
#                                  'icon': 'partly-cloudy-day',
#                                  'moonPhase': 0.02,
#                                  'ozone': 263.03,
#                                  'precipIntensity': 0.0008,
#                                  'precipIntensityMax': 0.0059,
#                                  'precipIntensityMaxTime': 1541624400,
#                                  'precipProbability': 0.11,
#                                  'precipType': 'rain',
#                                  'pressure': 1016.17,
#                                  'summary': 'Partly cloudy until evening.',
#                                  'sunriseTime': 1541591208,
#                                  'sunsetTime': 1541630572,
#                                  'temperatureHigh': 85.48,
#                                  'temperatureHighTime': 1541620800,
#                                  'temperatureLow': 68.93,
#                                  'temperatureLowTime': 1541674800,
#                                  'temperatureMax': 85.48,
#                                  'temperatureMaxTime': 1541620800,
#                                  'temperatureMin': 67.39,
#                                  'temperatureMinTime': 1541588400,
#                                  'time': 1541566800,
#                                  'uvIndex': 5,
#                                  'uvIndexTime': 1541606400,
#                                  'visibility': 10,
#                                  'windBearing': 78,
#                                  'windGust': 7.09,
#                                  'windGustTime': 1541602800,
#                                  'windSpeed': 1.03},
# {   'apparentTemperatureHigh': 88.37,
#                                  'apparentTemperatureHighTime': 1541703600,
#                                  'apparentTemperatureLow': 69,
#                                  'apparentTemperatureLowTime': 1541761200,
#                                  'apparentTemperatureMax': 88.37,
#                                  'apparentTemperatureMaxTime': 1541703600,
#                                  'apparentTemperatureMin': 70.2,
#                                  'apparentTemperatureMinTime': 1541674800,
#                                  'cloudCover': 0.26,
#                                  'dewPoint': 68.67,
#                                  'humidity': 0.78,
#                                  'icon': 'partly-cloudy-day',
#                                  'moonPhase': 0.04,
#                                  'ozone': 259.4,
#                                  'precipIntensity': 0.0017,
#                                  'precipIntensityMax': 0.0075,
#                                  'precipIntensityMaxTime': 1541721600,
#                                  'precipProbability': 0.18,
#                                  'precipType': 'rain',
#                                  'pressure': 1015.19,
#                                  'summary': 'Partly cloudy until afternoon.',
#                                  'sunriseTime': 1541677653,
#                                  'sunsetTime': 1541716937,
#                                  'temperatureHigh': 85.19,
#                                  'temperatureHighTime': 1541703600,
#                                  'temperatureLow': 67.95,
#                                  'temperatureLowTime': 1541761200,
#                                  'temperatureMax': 85.19,
#                                  'temperatureMaxTime': 1541703600,
#                                  'temperatureMin': 68.93,
#                                  'temperatureMinTime': 1541674800,
#                                  'time': 1541653200,
#                                  'uvIndex': 5,
#                                  'uvIndexTime': 1541692800,
#                                  'visibility': 10,
#                                  'windBearing': 3,
#                                  'windGust': 9.61,
#                                  'windGustTime': 1541732400,
#                                  'windSpeed': 2.62},
# {   'apparentTemperatureHigh': 87.38,
#                                  'apparentTemperatureHighTime': 1541790000,
#                                  'apparentTemperatureLow': 69.69,
#                                  'apparentTemperatureLowTime': 1541851200,
#                                  'apparentTemperatureMax': 87.38,
#                                  'apparentTemperatureMaxTime': 1541790000,
#                                  'apparentTemperatureMin': 69,
#                                  'apparentTemperatureMinTime': 1541761200,
#                                  'cloudCover': 0.02,
#                                  'dewPoint': 67.89,
#                                  'humidity': 0.77,
#                                  'icon': 'clear-day',
#                                  'moonPhase': 0.07,
#                                  'ozone': 256.93,
#                                  'precipIntensity': 0.0005,
#                                  'precipIntensityMax': 0.0039,
#                                  'precipIntensityMaxTime': 1541797200,
#                                  'precipProbability': 0.08,
#                                  'precipType': 'rain',
#                                  'pressure': 1014.99,
#                                  'summary': 'Clear throughout the day.',
#                                  'sunriseTime': 1541764099,
#                                  'sunsetTime': 1541803303,
#                                  'temperatureHigh': 84.25,
#                                  'temperatureHighTime': 1541790000,
#                                  'temperatureLow': 68.73,
#                                  'temperatureLowTime': 1541851200,
#                                  'temperatureMax': 84.25,
#                                  'temperatureMaxTime': 1541790000,
#                                  'temperatureMin': 67.95,
#                                  'temperatureMinTime': 1541761200,
#                                  'time': 1541739600,
#                                  'uvIndex': 6,
#                                  'uvIndexTime': 1541782800,
#                                  'visibility': 10,
#                                  'windBearing': 342,
#                                  'windGust': 14.36,
#                                  'windGustTime': 1541811600,
#                                  'windSpeed': 3.81},
# {   'apparentTemperatureHigh': 81.58,
#                                  'apparentTemperatureHighTime': 1541883600,
#                                  'apparentTemperatureLow': 68.37,
#                                  'apparentTemperatureLowTime': 1541934000,
#                                  'apparentTemperatureMax': 81.58,
#                                  'apparentTemperatureMaxTime': 1541883600,
#                                  'apparentTemperatureMin': 69.69,
#                                  'apparentTemperatureMinTime': 1541851200,
#                                  'cloudCover': 0.52,
#                                  'dewPoint': 65.32,
#                                  'humidity': 0.77,
#                                  'icon': 'partly-cloudy-night',
#                                  'moonPhase': 0.1,
#                                  'ozone': 254.95,
#                                  'precipIntensity': 0.0003,
#                                  'precipIntensityMax': 0.0016,
#                                  'precipIntensityMaxTime': 1541883600,
#                                  'precipProbability': 0.07,
#                                  'precipType': 'rain',
#                                  'pressure': 1017.91,
#                                  'summary': 'Mostly cloudy throughout the day.',
#                                  'sunriseTime': 1541850544,
#                                  'sunsetTime': 1541889670,
#                                  'temperatureHigh': 79.91,
#                                  'temperatureHighTime': 1541883600,
#                                  'temperatureLow': 67.44,
#                                  'temperatureLowTime': 1541934000,
#                                  'temperatureMax': 79.91,
#                                  'temperatureMaxTime': 1541883600,
#                                  'temperatureMin': 68.73,
#                                  'temperatureMinTime': 1541851200,
#                                  'time': 1541826000,
#                                  'uvIndex': 5,
#                                  'uvIndexTime': 1541869200,
#                                  'visibility': 10,
#                                  'windBearing': 34,
#                                  'windGust': 18.57,
#                                  'windGustTime': 1541851200,
#                                  'windSpeed': 10.49},
# {   'apparentTemperatureHigh': 83.13,
#                                  'apparentTemperatureHighTime': 1541966400,
#                                  'apparentTemperatureLow': 68.34,
#                                  'apparentTemperatureLowTime': 1542020400,
#                                  'apparentTemperatureMax': 83.13,
#                                  'apparentTemperatureMaxTime': 1541966400,
#                                  'apparentTemperatureMin': 68.37,
#                                  'apparentTemperatureMinTime': 1541934000,
#                                  'cloudCover': 0.67,
#                                  'dewPoint': 66.57,
#                                  'humidity': 0.81,
#                                  'icon': 'partly-cloudy-day',
#                                  'moonPhase': 0.13,
#                                  'ozone': 258.12,
#                                  'precipIntensity': 0.0015,
#                                  'precipIntensityMax': 0.008,
#                                  'precipIntensityMaxTime': 1541980800,
#                                  'precipProbability': 0.18,
#                                  'precipType': 'rain',
#                                  'pressure': 1019.21,
#                                  'summary': 'Mostly cloudy until evening.',
#                                  'sunriseTime': 1541936991,
#                                  'sunsetTime': 1541976039,
#                                  'temperatureHigh': 80.71,
#                                  'temperatureHighTime': 1541966400,
#                                  'temperatureLow': 67.5,
#                                  'temperatureLowTime': 1542020400,
#                                  'temperatureMax': 80.71,
#                                  'temperatureMaxTime': 1541966400,
#                                  'temperatureMin': 67.44,
#                                  'temperatureMinTime': 1541934000,
#                                  'time': 1541912400,
#                                  'uvIndex': 4,
#                                  'uvIndexTime': 1541952000,
#                                  'visibility': 10,
#                                  'windBearing': 48,
#                                  'windGust': 19.01,
#                                  'windGustTime': 1541995200,
#                                  'windSpeed': 11.64},
# {   'apparentTemperatureHigh': 77.56,
#                                  'apparentTemperatureHighTime': 1542045600,
#                                  'apparentTemperatureLow': 62.63,
#                                  'apparentTemperatureLowTime': 1542110400,
#                                  'apparentTemperatureMax': 77.56,
#                                  'apparentTemperatureMaxTime': 1542045600,
#                                  'apparentTemperatureMin': 68.34,
#                                  'apparentTemperatureMinTime': 1542020400,
#                                  'cloudCover': 0.72,
#                                  'dewPoint': 65.53,
#                                  'humidity': 0.82,
#                                  'icon': 'partly-cloudy-day',
#                                  'moonPhase': 0.16,
#                                  'ozone': 257.74,
#                                  'precipIntensity': 0.0063,
#                                  'precipIntensityMax': 0.0231,
#                                  'precipIntensityMaxTime': 1542056400,
#                                  'precipProbability': 0.5,
#                                  'precipType': 'rain',
#                                  'pressure': 1019.2,
#                                  'summary': 'Mostly cloudy throughout the day.',
#                                  'sunriseTime': 1542023437,
#                                  'sunsetTime': 1542062409,
#                                  'temperatureHigh': 76.91,
#                                  'temperatureHighTime': 1542045600,
#                                  'temperatureLow': 62.63,
#                                  'temperatureLowTime': 1542110400,
#                                  'temperatureMax': 76.91,
#                                  'temperatureMaxTime': 1542045600,
#                                  'temperatureMin': 67.5,
#                                  'temperatureMinTime': 1542020400,
#                                  'time': 1541998800,
#                                  'uvIndex': 4,
#                                  'uvIndexTime': 1542038400,
#                                  'visibility': 10,
#                                  'windBearing': 62,
#                                  'windGust': 18.91,
#                                  'windGustTime': 1541998800,
#                                  'windSpeed': 9.94}],
#                  'icon': 'clear-day',
#                  'summary': 'No precipitation throughout the week, with high '
#                             'temperatures peaking at 85°F on Wednesday.'},