from datetime import date
import time
import math

# Since DarkySky does not have icons available online to be used, the 'icon' value returned by the DarkSky API is mapped
# to a similar open weather icon. Open weather icons are available online and can be used in html with the following:
# <img src="http://openweathermap.org/img/w/[ICON_VALUE].png" alt="Image">
DARKSKY_TO_OPEN_WEATHER_ICON = {
        "clear-day": "01d",
        "clear-night": "01n",
        "rain": "09d",
        "snow": "13d",
        "sleet": "09d",
        "wind": "50d",
        "fog": "04d",
        "cloudy": "03d",
        "partly-cloudy-day": "02d",
        "partly-cloudy-night": "02n",
        "hail": "11d",
        "thunderstorm": "11d",
        "tornado": "11d"
}

# Convert epoch time value to day of the week (Sunday, Monday, Tuesday, etc.)
# Used by get_week_weather to convert time values to days for display
def convert_epoch_time_to_day_of_the_week(epoch_time_in_seconds):
    d = date.fromtimestamp(epoch_time_in_seconds)
    return d.strftime('%A')

# Convert epoch time value to 12hr time (12PM, 1PM, 2PM, etc.)
# Used by get_day_weather to convert eepoch time values to human readable times for display
def convert_epoch_time_to_hour_of_the_day(epoch_time_in_seconds):
    # time.strftime will give us a 24hr time (00:00-24:00), so this dict maps 24 hour times to 12 hour times -- there
    # is probably an easier/more elegant way to convert times, but this method works
    time24hr_to_time12hr = {"00:00": "12:00 AM", "01:00":  "1:00 AM", "02:00": "2:00 AM", "03:00": "3:00 AM",
                            "04:00": "4:00 AM", "05:00": "5:00 AM", "06:00": "6:00 AM", "07:00": "7:00 AM",
                            "08:00": "8:00 AM", "09:00": "9:00 AM", "10:00": "10:00 AM", "11:00": "11:00 AM",
                            "12:00": "12:00 PM", "13:00": "1:00 PM", "14:00": "2:00 PM", "15:00": "3:00 PM",
                            "16:00": "4:00 PM", "17:00": "5:00 PM", "18:00": "6:00 PM", "19:00": "7:00 PM",
                            "20:00": "8:00 PM", "21:00": "9:00 PM", "22:00": "10:00 PM", "23:00": "11:00 PM",
                            "24:00": "12:00 PM"}
    return time24hr_to_time12hr[time.strftime('%H:%M', time.localtime(epoch_time_in_seconds))]


# Gives current weather forecast -- basic data
def get_current_weather_basic(darkskyjson, city):
    current_weather = {
        "city": city,
        "icon": DARKSKY_TO_OPEN_WEATHER_ICON[darkskyjson["currently"]["icon"]],
        "time": darkskyjson["currently"]["time"],
        "summary": darkskyjson["currently"]["summary"],
        "precipProbability": darkskyjson["currently"]["precipProbability"],
        "temperature": math.ceil(darkskyjson["currently"]["temperature"]),
        "humidity": darkskyjson["currently"]["humidity"],
        "windSpeed": darkskyjson["currently"]["windSpeed"],
        "windGust": darkskyjson["currently"]["windGust"],
        "visibility": darkskyjson["currently"]["visibility"],
    }
    return current_weather

# Gives current weather forecast -- all data
# See DarkSky documentation for json format: https://darksky.net/dev/docs
def get_current_weather_all(darkskyjson):
    return darkskyjson["currently"]

# Gives summary of weather for the day in hourly weather forecast. The hourly_weather object here will contain
# 7 different forecasts, with weather data from the present hour then every 3 hours.
def get_day_weather_basic(darkskyjson, city):

    hours = []
    for i in range (0, 24, 1):
        hours.append({
            "icon": DARKSKY_TO_OPEN_WEATHER_ICON[darkskyjson["hourly"]["data"][i]["icon"]],
            "time": convert_epoch_time_to_hour_of_the_day(darkskyjson["hourly"]["data"][i]["time"]),
            "summary": darkskyjson["hourly"]["data"][i]["summary"],
            "temperature": math.ceil(darkskyjson["hourly"]["data"][i]["temperature"]),
            "humidity": math.ceil(darkskyjson["hourly"]["data"][i]["humidity"] * 100),
            "precipProbability": math.ceil(darkskyjson["hourly"]["data"][i]["precipProbability"] * 100),
            "windSpeed": math.ceil(darkskyjson["hourly"]["data"][i]["windSpeed"]),
        })

    hourly_weather = {
        "city": city,
        "daySummary": darkskyjson["hourly"]["summary"],
        "icon": DARKSKY_TO_OPEN_WEATHER_ICON[darkskyjson["hourly"]["icon"]],
        "hours": hours
    }
    return hourly_weather

# Gives weather data for day in hourly weather forecasts (over 40)
# See DarkSky documentation for json format: https://darksky.net/dev/docs
def get_day_weather_all(darkskyjson):
    return darkskyjson["hourly"]

# Gives summary of weather for the week by daily forecasts -- basic data
def get_week_weather_basic(darkskyjson, city):

    days = []
    for i in range(0, 8):
        days.append({
            "icon": DARKSKY_TO_OPEN_WEATHER_ICON[darkskyjson["daily"]["data"][i]["icon"]],
            "time": convert_epoch_time_to_day_of_the_week(darkskyjson["daily"]["data"][i]["time"]),
            "summary": darkskyjson["daily"]["data"][i]["summary"],
            "precipProbability": math.ceil(darkskyjson["daily"]["data"][i]["precipProbability"] * 100),
#            "precipType": darkskyjson["daily"]["data"][i]["precipType"],
            "temperatureHigh": math.ceil(darkskyjson["daily"]["data"][i]["temperatureHigh"]),
            "temperatureLow": math.ceil(darkskyjson["daily"]["data"][i]["temperatureLow"]),
            "humidity": math.ceil(darkskyjson["daily"]["data"][i]["humidity"] * 100),
            "windSpeed": math.ceil(darkskyjson["daily"]["data"][i]["windSpeed"]),
            "windGust": darkskyjson["daily"]["data"][i]["windGust"],
            "visibility": darkskyjson["daily"]["data"][i]["visibility"]
        })

    weekly_weather = {
        "city": city,
        "weekSummary": darkskyjson["daily"]["summary"],
        "icon": DARKSKY_TO_OPEN_WEATHER_ICON[darkskyjson["daily"]["icon"]],
        "days": days,
    }
    return weekly_weather

# Gives summary of weather for the week, and daily forecasts for the week -- all data
# See end of file for all data json structure -- DarkSky documentation for json format https://darksky.net/dev/docs
# appears to be outdated and slightly off.
def get_week_weather_all(darkskyjson):
    return darkskyjson["daily"]

# Example structure returned from get_day_weather_all:
#     'hourly': {   'data': [   {   'apparentTemperature': 86.88,
#                                   'cloudCover': 0.56,
#                                   'dewPoint': 68.41,
#                                   'humidity': 0.61,
#                                   'icon': 'partly-cloudy-day',
#                                   'ozone': 253.5,
#                                   'precipIntensity': 0,
#                                   'precipProbability': 0,
#                                   'pressure': 1017.52,
#                                   'summary': 'Partly Cloudy',
#                                   'temperature': 83.52,
#                                   'time': 1541440800, 1PM
#                                   'uvIndex': 5,
#                                   'visibility': 10,
#                                   'windBearing': 168,
#                                   'windGust': 5.13,
#                                   'windSpeed': 3.57
#                               },
#                                   ...
#                                   The structure containing all data includes over 40 entries for hourly weather data
#                                   Only the first and last are shown in this example to reduce size.
#                                   ...
#                               {
#                                 'apparentTemperature': 87.09,
#                                 'cloudCover': 0.34,
#                                'dewPoint': 66.67,
#                                'humidity': 0.55,
#                                'icon': 'partly-cloudy-day',
#                                'ozone': 264.47,
#                                'precipIntensity': 0,
#                                'precipProbability': 0,
#                                'pressure': 1015.92,
#                                'summary': 'Partly Cloudy',
#                                'temperature': 84.51,
#                                'time': 1541613600,
#                                'uvIndex': 5,
#                                'visibility': 10,
#                                'windBearing': 158,
#                                'windGust': 6.37,
#                                'windSpeed': 4.43
#                           }
#                    ],
#                   'icon': 'partly-cloudy-night',
#                   'summary': 'Mostly cloudy throughout the day.'
#     }

# Example structure returned from get_week_weather_all:
# 'daily': {
#
# 	'data': [
# {   'apparentTemperatureHigh': 87.79,
#                                  'apparentTemperatureHighTime': 1541448000,
#                                  'apparentTemperatureLow': 71.54,
#                                  'apparentTemperatureLowTime': 1541502000,
#                                  'apparentTemperatureMax': 87.79,
#                                  'apparentTemperatureMaxTime': 1541448000,
#                                  'apparentTemperatureMin': 73.56,
#                                  'apparentTemperatureMinTime': 1541397600,
#                                  'cloudCover': 0.53,
#                                  'dewPoint': 69.62,
#                                  'humidity': 0.79,
#                                  'icon': 'partly-cloudy-night',
#                                  'moonPhase': 0.93,
#                                  'ozone': 251.88,
#                                  'precipIntensity': 0.0007,
#                                  'precipIntensityMax': 0.0025,
#                                  'precipIntensityMaxTime': 1541462400,
#                                  'precipProbability': 0.19,
#                                  'precipType': 'rain',
#                                  'pressure': 1017.48,
#                                  'summary': 'Mostly cloudy throughout the day.',
#                                  'sunriseTime': 1541418318,
#                                  'sunsetTime': 1541457847,
#                                  'temperatureHigh': 84.84,
#                                  'temperatureHighTime': 1541448000,
#                                  'temperatureLow': 70.26,
#                                  'temperatureLowTime': 1541502000,
#                                  'temperatureMax': 84.84,
#                                  'temperatureMaxTime': 1541448000,
#                                  'temperatureMin': 72.24,
#                                  'temperatureMinTime': 1541397600,
#                                  'time': 1541394000,
#                                  'uvIndex': 5,
#                                  'uvIndexTime': 1541433600,
#                                  'visibility': 10,
#                                  'windBearing': 152,
#                                  'windGust': 7.79,
#                                  'windGustTime': 1541458800,
#                                  'windSpeed': 3.77},
# {   'apparentTemperatureHigh': 87.37,
#                                  'apparentTemperatureHighTime': 1541534400,
#                                  'apparentTemperatureLow': 68.53,
#                                  'apparentTemperatureLowTime': 1541588400,
#                                  'apparentTemperatureMax': 87.37,
#                                  'apparentTemperatureMaxTime': 1541534400,
#                                  'apparentTemperatureMin': 71.54,
#                                  'apparentTemperatureMinTime': 1541502000,
#                                  'cloudCover': 0.71,
#                                  'dewPoint': 68.59,
#                                  'humidity': 0.78,
#                                  'icon': 'partly-cloudy-day',
#                                  'moonPhase': 0.97,
#                                  'ozone': 257.27,
#                                  'precipIntensity': 0.0007,
#                                  'precipIntensityMax': 0.0042,
#                                  'precipIntensityMaxTime': 1541494800,
#                                  'precipProbability': 0.16,
#                                  'precipType': 'rain',
#                                  'pressure': 1016.57,
#                                  'summary': 'Mostly cloudy throughout the day.',
#                                  'sunriseTime': 1541504763,
#                                  'sunsetTime': 1541544209,
#                                  'temperatureHigh': 85,
#                                  'temperatureHighTime': 1541534400,
#                                  'temperatureLow': 67.39,
#                                  'temperatureLowTime': 1541588400,
#                                  'temperatureMax': 85,
#                                  'temperatureMaxTime': 1541534400,
#                                  'temperatureMin': 70.26,
#                                  'temperatureMinTime': 1541502000,
#                                  'time': 1541480400,
#                                  'uvIndex': 5,
#                                  'uvIndexTime': 1541523600,
#                                  'visibility': 10,
#                                  'windBearing': 162,
#                                  'windGust': 10.64,
#                                  'windGustTime': 1541512800,
#                                  'windSpeed': 2.99},
# {   'apparentTemperatureHigh': 87.69,
#                                  'apparentTemperatureHighTime': 1541620800,
#                                  'apparentTemperatureLow': 70.2,
#                                  'apparentTemperatureLowTime': 1541674800,
#                                  'apparentTemperatureMax': 87.69,
#                                  'apparentTemperatureMaxTime': 1541620800,
#                                  'apparentTemperatureMin': 68.53,
#                                  'apparentTemperatureMinTime': 1541588400,
#                                  'cloudCover': 0.25,
#                                  'dewPoint': 68.08,
#                                  'humidity': 0.79,
#                                  'icon': 'partly-cloudy-day',
#                                  'moonPhase': 0.02,
#                                  'ozone': 263.03,
#                                  'precipIntensity': 0.0008,
#                                  'precipIntensityMax': 0.0059,
#                                  'precipIntensityMaxTime': 1541624400,
#                                  'precipProbability': 0.11,
#                                  'precipType': 'rain',
#                                  'pressure': 1016.17,
#                                  'summary': 'Partly cloudy until evening.',
#                                  'sunriseTime': 1541591208,
#                                  'sunsetTime': 1541630572,
#                                  'temperatureHigh': 85.48,
#                                  'temperatureHighTime': 1541620800,
#                                  'temperatureLow': 68.93,
#                                  'temperatureLowTime': 1541674800,
#                                  'temperatureMax': 85.48,
#                                  'temperatureMaxTime': 1541620800,
#                                  'temperatureMin': 67.39,
#                                  'temperatureMinTime': 1541588400,
#                                  'time': 1541566800,
#                                  'uvIndex': 5,
#                                  'uvIndexTime': 1541606400,
#                                  'visibility': 10,
#                                  'windBearing': 78,
#                                  'windGust': 7.09,
#                                  'windGustTime': 1541602800,
#                                  'windSpeed': 1.03},
# {   'apparentTemperatureHigh': 88.37,
#                                  'apparentTemperatureHighTime': 1541703600,
#                                  'apparentTemperatureLow': 69,
#                                  'apparentTemperatureLowTime': 1541761200,
#                                  'apparentTemperatureMax': 88.37,
#                                  'apparentTemperatureMaxTime': 1541703600,
#                                  'apparentTemperatureMin': 70.2,
#                                  'apparentTemperatureMinTime': 1541674800,
#                                  'cloudCover': 0.26,
#                                  'dewPoint': 68.67,
#                                  'humidity': 0.78,
#                                  'icon': 'partly-cloudy-day',
#                                  'moonPhase': 0.04,
#                                  'ozone': 259.4,
#                                  'precipIntensity': 0.0017,
#                                  'precipIntensityMax': 0.0075,
#                                  'precipIntensityMaxTime': 1541721600,
#                                  'precipProbability': 0.18,
#                                  'precipType': 'rain',
#                                  'pressure': 1015.19,
#                                  'summary': 'Partly cloudy until afternoon.',
#                                  'sunriseTime': 1541677653,
#                                  'sunsetTime': 1541716937,
#                                  'temperatureHigh': 85.19,
#                                  'temperatureHighTime': 1541703600,
#                                  'temperatureLow': 67.95,
#                                  'temperatureLowTime': 1541761200,
#                                  'temperatureMax': 85.19,
#                                  'temperatureMaxTime': 1541703600,
#                                  'temperatureMin': 68.93,
#                                  'temperatureMinTime': 1541674800,
#                                  'time': 1541653200,
#                                  'uvIndex': 5,
#                                  'uvIndexTime': 1541692800,
#                                  'visibility': 10,
#                                  'windBearing': 3,
#                                  'windGust': 9.61,
#                                  'windGustTime': 1541732400,
#                                  'windSpeed': 2.62},
# {   'apparentTemperatureHigh': 87.38,
#                                  'apparentTemperatureHighTime': 1541790000,
#                                  'apparentTemperatureLow': 69.69,
#                                  'apparentTemperatureLowTime': 1541851200,
#                                  'apparentTemperatureMax': 87.38,
#                                  'apparentTemperatureMaxTime': 1541790000,
#                                  'apparentTemperatureMin': 69,
#                                  'apparentTemperatureMinTime': 1541761200,
#                                  'cloudCover': 0.02,
#                                  'dewPoint': 67.89,
#                                  'humidity': 0.77,
#                                  'icon': 'clear-day',
#                                  'moonPhase': 0.07,
#                                  'ozone': 256.93,
#                                  'precipIntensity': 0.0005,
#                                  'precipIntensityMax': 0.0039,
#                                  'precipIntensityMaxTime': 1541797200,
#                                  'precipProbability': 0.08,
#                                  'precipType': 'rain',
#                                  'pressure': 1014.99,
#                                  'summary': 'Clear throughout the day.',
#                                  'sunriseTime': 1541764099,
#                                  'sunsetTime': 1541803303,
#                                  'temperatureHigh': 84.25,
#                                  'temperatureHighTime': 1541790000,
#                                  'temperatureLow': 68.73,
#                                  'temperatureLowTime': 1541851200,
#                                  'temperatureMax': 84.25,
#                                  'temperatureMaxTime': 1541790000,
#                                  'temperatureMin': 67.95,
#                                  'temperatureMinTime': 1541761200,
#                                  'time': 1541739600,
#                                  'uvIndex': 6,
#                                  'uvIndexTime': 1541782800,
#                                  'visibility': 10,
#                                  'windBearing': 342,
#                                  'windGust': 14.36,
#                                  'windGustTime': 1541811600,
#                                  'windSpeed': 3.81},
# {   'apparentTemperatureHigh': 81.58,
#                                  'apparentTemperatureHighTime': 1541883600,
#                                  'apparentTemperatureLow': 68.37,
#                                  'apparentTemperatureLowTime': 1541934000,
#                                  'apparentTemperatureMax': 81.58,
#                                  'apparentTemperatureMaxTime': 1541883600,
#                                  'apparentTemperatureMin': 69.69,
#                                  'apparentTemperatureMinTime': 1541851200,
#                                  'cloudCover': 0.52,
#                                  'dewPoint': 65.32,
#                                  'humidity': 0.77,
#                                  'icon': 'partly-cloudy-night',
#                                  'moonPhase': 0.1,
#                                  'ozone': 254.95,
#                                  'precipIntensity': 0.0003,
#                                  'precipIntensityMax': 0.0016,
#                                  'precipIntensityMaxTime': 1541883600,
#                                  'precipProbability': 0.07,
#                                  'precipType': 'rain',
#                                  'pressure': 1017.91,
#                                  'summary': 'Mostly cloudy throughout the day.',
#                                  'sunriseTime': 1541850544,
#                                  'sunsetTime': 1541889670,
#                                  'temperatureHigh': 79.91,
#                                  'temperatureHighTime': 1541883600,
#                                  'temperatureLow': 67.44,
#                                  'temperatureLowTime': 1541934000,
#                                  'temperatureMax': 79.91,
#                                  'temperatureMaxTime': 1541883600,
#                                  'temperatureMin': 68.73,
#                                  'temperatureMinTime': 1541851200,
#                                  'time': 1541826000,
#                                  'uvIndex': 5,
#                                  'uvIndexTime': 1541869200,
#                                  'visibility': 10,
#                                  'windBearing': 34,
#                                  'windGust': 18.57,
#                                  'windGustTime': 1541851200,
#                                  'windSpeed': 10.49},
# {   'apparentTemperatureHigh': 83.13,
#                                  'apparentTemperatureHighTime': 1541966400,
#                                  'apparentTemperatureLow': 68.34,
#                                  'apparentTemperatureLowTime': 1542020400,
#                                  'apparentTemperatureMax': 83.13,
#                                  'apparentTemperatureMaxTime': 1541966400,
#                                  'apparentTemperatureMin': 68.37,
#                                  'apparentTemperatureMinTime': 1541934000,
#                                  'cloudCover': 0.67,
#                                  'dewPoint': 66.57,
#                                  'humidity': 0.81,
#                                  'icon': 'partly-cloudy-day',
#                                  'moonPhase': 0.13,
#                                  'ozone': 258.12,
#                                  'precipIntensity': 0.0015,
#                                  'precipIntensityMax': 0.008,
#                                  'precipIntensityMaxTime': 1541980800,
#                                  'precipProbability': 0.18,
#                                  'precipType': 'rain',
#                                  'pressure': 1019.21,
#                                  'summary': 'Mostly cloudy until evening.',
#                                  'sunriseTime': 1541936991,
#                                  'sunsetTime': 1541976039,
#                                  'temperatureHigh': 80.71,
#                                  'temperatureHighTime': 1541966400,
#                                  'temperatureLow': 67.5,
#                                  'temperatureLowTime': 1542020400,
#                                  'temperatureMax': 80.71,
#                                  'temperatureMaxTime': 1541966400,
#                                  'temperatureMin': 67.44,
#                                  'temperatureMinTime': 1541934000,
#                                  'time': 1541912400,
#                                  'uvIndex': 4,
#                                  'uvIndexTime': 1541952000,
#                                  'visibility': 10,
#                                  'windBearing': 48,
#                                  'windGust': 19.01,
#                                  'windGustTime': 1541995200,
#                                  'windSpeed': 11.64},
# {   'apparentTemperatureHigh': 77.56,
#                                  'apparentTemperatureHighTime': 1542045600,
#                                  'apparentTemperatureLow': 62.63,
#                                  'apparentTemperatureLowTime': 1542110400,
#                                  'apparentTemperatureMax': 77.56,
#                                  'apparentTemperatureMaxTime': 1542045600,
#                                  'apparentTemperatureMin': 68.34,
#                                  'apparentTemperatureMinTime': 1542020400,
#                                  'cloudCover': 0.72,
#                                  'dewPoint': 65.53,
#                                  'humidity': 0.82,
#                                  'icon': 'partly-cloudy-day',
#                                  'moonPhase': 0.16,
#                                  'ozone': 257.74,
#                                  'precipIntensity': 0.0063,
#                                  'precipIntensityMax': 0.0231,
#                                  'precipIntensityMaxTime': 1542056400,
#                                  'precipProbability': 0.5,
#                                  'precipType': 'rain',
#                                  'pressure': 1019.2,
#                                  'summary': 'Mostly cloudy throughout the day.',
#                                  'sunriseTime': 1542023437,
#                                  'sunsetTime': 1542062409,
#                                  'temperatureHigh': 76.91,
#                                  'temperatureHighTime': 1542045600,
#                                  'temperatureLow': 62.63,
#                                  'temperatureLowTime': 1542110400,
#                                  'temperatureMax': 76.91,
#                                  'temperatureMaxTime': 1542045600,
#                                  'temperatureMin': 67.5,
#                                  'temperatureMinTime': 1542020400,
#                                  'time': 1541998800,
#                                  'uvIndex': 4,
#                                  'uvIndexTime': 1542038400,
#                                  'visibility': 10,
#                                  'windBearing': 62,
#                                  'windGust': 18.91,
#                                  'windGustTime': 1541998800,
#                                  'windSpeed': 9.94}],
#                  'icon': 'clear-day',
#                  'summary': 'No precipitation throughout the week, with high '
#                             'temperatures peaking at 85°F on Wednesday.'},